name: quotebrowser
description: Quotes browser.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #============================================================================AL
  ##----layout
  card_swiper: ^3.0.1 #https://pub.dev/packages/card_swiper

  searchable_listview: ^2.7.0 #https://pub.dev/packages/searchable_listview
  expandable: ^5.0.1 #https://pub.dev/packages/expandable
  pluto_menu_bar: ^3.0.1 #https://pub.dev/packages/pluto_menu_bar
  buttons_tabbar: ^1.3.8 #https://pub.dev/packages/buttons_tabbar
  awesome_snackbar_content: ^0.1.3 #https://pub.dev/packages/awesome_snackbar_content

  ##-------------------------------------------tables,grid
  pluto_grid: ^7.0.2 #https://pub.dev/packages/pluto_grid

  ##----text
  ##frozen problem!! highlight_text: ^1.7.0 #https://pub.dev/packages/highlight_text
  tag_highlight_text: ^1.0.2 #https://pub.dev/packages/tag_highlight_text
  input_dialog: ^0.1.1 #https://pub.dev/packages/input_dialog
  clipboard: ^0.1.3 #https://pub.dev/packages/clipboard
  rich_readmore: ^1.0.6 #https://pub.dev/packages/rich_readmore

  ##----elements
  dropdown_button2: ^2.3.9 #https://pub.dev/packages/dropdown_button2
  flutter_rating_stars: ^1.0.3+4 #https://pub.dev/packages/flutter_rating_stars
  multi_select_flutter: ^4.1.3 #https://pub.dev/packages/multi_select_flutter

  #============================================================================BL
  ##-----bl status
  get: ^4.6.5 #https://pub.dev/packages/get

  ##----db
  shared_preferences: ^2.2.2

  sqflite: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2+3
  sqflite_common_ffi: ^2.3.2+1

  supabase_flutter: ^2.3.4 #https://pub.dev/packages/supabase_flutter
  supabase_extensions: ^1.0.0 #https://pub.dev/packages/supabase_extensions

  postgres: ^3.1.1 #https://pub.dev/packages/postgres

  #cloud_firestore: ^4.15.8 #https://pub.dev/packages/cloud_firestore
  #cloud_firestore_api: ^0.0.9
  # firebase_core: ^2.27.0
  # firebase_auth: ^4.17.8
  #============================================================================DL

  ##----url
  flutter_linkify: ^6.0.0 #https://pub.dev/packages/flutter_linkify
  url_launcher: ^6.2.4 #https://pub.dev/packages/url_launcher
  dio: ^5.3.2 #https://pub.dev/packages/dio

  #----------------------------------------------uti
  intl: ^0.18.1 #https://pub.dev/packages/intl
  dartx: ^1.2.0 #https://pub.dev/packages/dartx
  csv: ^5.1.1 #https://pub.dev/packages/csv
  device_info_plus: ^9.1.1

  ##----icons, buttons
  fluentui_system_icons: ^1.1.210 #https://pub.dev/packages/fluentui_system_icons
  cupertino_icons: ^1.0.5 #https://pub.dev/packages/cupertino_icons
  holdable_button: ^0.0.9 #https://pub.dev/packages/holdable_button
#******************************************************************************DEV
dev_dependencies:
  analyzer: 5.13.0

  #build_runner: any   #dart run build_runner build
  build_runner: ^2.4.7
  drift_dev: ^2.14.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #-----------------------------------------assets
  assets:
    - assets/data/
