name: quotebrowser
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  ##----db
  isar: 4.0.0-dev.6
  isar_flutter_libs: 4.0.0-dev.6

dev_dependencies:
  build_runner: any

  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
