name: quotebrowser
description: Quotes browser.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #============================================================================AL
  ##----layout
  card_swiper: ^3.0.1                     #https://pub.dev/packages/card_swiper
  
  
  searchable_listview: ^2.7.0             #https://pub.dev/packages/searchable_listview
  expandable: ^5.0.1                      #https://pub.dev/packages/expandable
  pluto_menu_bar: ^3.0.1                  #https://pub.dev/packages/pluto_menu_bar
  
  collapsible_sidebar: ^2.0.5+1           #https://pub.dev/packages/collapsible_sidebar
  
  ##----text
  highlight_text: ^1.7.0                  #https://pub.dev/packages/highlight_text


  ##----elements
  dropdown_button2: ^2.3.8                #https://pub.dev/packages/dropdown_button2
  flutter_rating_stars: ^1.0.3+4          #https://pub.dev/packages/flutter_rating_stars
  
  ##----url
  flutter_linkify: ^6.0.0                 #https://pub.dev/packages/flutter_linkify
  url_launcher: ^6.1.12                   #https://pub.dev/packages/url_launcher
  clipboard: ^0.1.3                       #https://pub.dev/packages/clipboard
  translator_plus: ^1.0.1                 #https://pub.dev/packages/translator_plus
 
  #============================================================================BL  
  ##-----bl status
  get: ^4.6.5                             #https://pub.dev/packages/get  

  ##----db
  isar: ^4.0.0-dev.14                     #https://pub.dev/packages/isar/versions/4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  #============================================================================DL
  dio: ^5.3.2                             #https://pub.dev/packages/dio

  #----------------------------------------------uti
  intl: ^0.18.1                           #https://pub.dev/packages/intl
  dartx: ^1.2.0                           #https://pub.dev/packages/dartx
  csv: ^5.0.2                             #https://pub.dev/packages/csv

    
  ##----icons
  fluentui_system_icons: ^1.1.210         #https://pub.dev/packages/fluentui_system_icons
  cupertino_icons: ^1.0.5                 #https://pub.dev/packages/cupertino_icons


#******************************************************************************DEV  
dev_dependencies:
  build_runner: any

  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

