name: quotebrowser
description: Quotes browser.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #============================================================================AL
  ##----layout
  card_swiper: ^3.0.1 #https://pub.dev/packages/card_swiper

  searchable_listview: ^2.7.0 #https://pub.dev/packages/searchable_listview
  expandable: ^5.0.1 #https://pub.dev/packages/expandable
  pluto_menu_bar: ^3.0.1 #https://pub.dev/packages/pluto_menu_bar

  grouped_scroll_view: ^0.0.10 #https://pub.dev/packages/grouped_scroll_view
  awesome_snackbar_content: ^0.1.3 #https://pub.dev/packages/awesome_snackbar_content

  ##----text
  highlight_text: ^1.7.0 #https://pub.dev/packages/highlight_text
  input_dialog: ^0.1.1 #https://pub.dev/packages/input_dialog
  clipboard: ^0.1.3 #https://pub.dev/packages/clipboard
  rich_readmore: ^1.0.6 #https://pub.dev/packages/rich_readmore

  ##----elements
  dropdown_button2: ^2.3.8 #https://pub.dev/packages/dropdown_button2
  flutter_rating_stars: ^1.0.3+4 #https://pub.dev/packages/flutter_rating_stars

  #============================================================================BL
  ##-----bl status
  get: ^4.6.5 #https://pub.dev/packages/get

  ##----db
  isar: ^4.0.0-dev.14 #https://pub.dev/packages/isar/versions/4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14

  drift: ^2.14.1 #https://pub.dev/packages/drift
  drift_db_viewer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.3.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  path_provider: ^2.1.1
  #============================================================================DL

  ##----url
  flutter_linkify: ^6.0.0 #https://pub.dev/packages/flutter_linkify
  url_launcher: ^6.1.12 #https://pub.dev/packages/url_launcher
  dart_rss: ^3.0.1 #https://pub.dev/packages/dart_rss
  dio: ^5.3.2 #https://pub.dev/packages/dio

  #----------------------------------------------uti
  intl: ^0.18.1 #https://pub.dev/packages/intl
  dartx: ^1.2.0 #https://pub.dev/packages/dartx
  csv: ^5.0.2 #https://pub.dev/packages/csv
  device_info_plus: ^9.1.1

  ##----icons
  fluentui_system_icons: ^1.1.210 #https://pub.dev/packages/fluentui_system_icons
  cupertino_icons: ^1.0.5 #https://pub.dev/packages/cupertino_icons
  http: ^0.13.6

#******************************************************************************DEV
dev_dependencies:
  analyzer: 5.13.0

  #build_runner: any   #dart run build_runner build
  build_runner: ^2.4.7

  drift_dev: ^2.14.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
