name: quotebrowser
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #============================================================================AL
  ##----layout
  card_swiper: ^3.0.1                     #https://pub.dev/packages/card_swiper
  searchable_listview: ^2.5.0             #https://pub.dev/packages/searchable_listview
  expandable: ^5.0.1                      #https://pub.dev/packages/expandable
  pluto_menu_bar: ^3.0.1                  #https://pub.dev/packages/pluto_menu_bar
  easy_sidemenu: ^0.5.0                   #https://pub.dev/packages/easy_sidemenu
  
  ##----text
  highlight_text: ^1.7.0                  #https://pub.dev/packages/highlight_text

  ##----url
  flutter_linkify: ^6.0.0                 #https://pub.dev/packages/flutter_linkify
  url_launcher: ^6.1.12                   #https://pub.dev/packages/url_launcher
  clipboard: ^0.1.3                       #https://pub.dev/packages/clipboard
  #============================================================================BL  
  ##-----bl status
  get: ^4.6.5                             #https://pub.dev/packages/get

  ##----db
  isar: ^4.0.0-dev.9                      #https://pub.dev/packages/isar/versions/4.0.0-dev.9
  isar_flutter_libs: 4.0.0-dev.9
  

  #============================================================================DL
  gsheets: ^0.5.0 

  #----------------------------------------------uti
  intl: ^0.18.1                           #https://pub.dev/packages/intl
  dartx: ^1.2.0                           #https://pub.dev/packages/dartx
  csv: ^5.0.2                             #https://pub.dev/packages/csv
  cupertino_icons: ^1.0.5                 #https://pub.dev/packages/cupertino_icons


#******************************************************************************DEV  
dev_dependencies:
  build_runner: any

  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

